// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/labstack/echo/v4"
	"github.com/lightpub-dev/lightpub/db"
	"github.com/lightpub-dev/lightpub/users"
)

// Injectors from services.go:

func initializeUserCreateService(c echo.Context, h *Handler) *users.DBUserCreateService {
	context := db.ProvideContext(c)
	dbConn := ProvideDBConnFromHandler(context, h)
	dbUserCreateService := users.ProvideDBUserCreateService(dbConn)
	return dbUserCreateService
}

func initializeUserLoginService(c echo.Context, h *Handler) *users.DBUserLoginService {
	context := db.ProvideContext(c)
	dbConn := ProvideDBConnFromHandler(context, h)
	dbUserLoginService := users.ProvideDBUserLoginService(dbConn)
	return dbUserLoginService
}

// services.go:

func ProvideDBConnFromHandler(ctx db.Context, h *Handler) db.DBConn {
	return db.DBConn{DB: h.DB, Ctx: ctx}
}
