service:
  database:
    host: 127.0.0.1
    port: 3306
    user: lightpub
    pass: lightpub
    name: lightpub
  upload_dir: ./uploads
  dev_mode: true
auth:
  jwt_private_key_path: "data/jwt.pem"
  jwt_public_key_path: "data/jwtpub.pem"
registration_open: true
