services:
  lightpub_app:
    container_name: lightpub_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: debug
    profiles:
      - lightpub
    volumes:
      - ./test_instances/lightpub/config.fed.yaml:/app/config.yaml:ro
    networks:
      - internal_network
      - external_network

  lightpub_db:
    container_name: lightpub_db
    profiles:
      - lightpub
    networks:
      - internal_network
      - external_network

  lightpub_kv:
    container_name: lightpub_kv
    profiles:
      - lightpub
    networks:
      - internal_network
      - external_network

  lightpub_nats:
    container_name: lightpub_nats
    profiles:
      - lightpub
    networks:
      - internal_network
      - external_network

  lightpub_typesense:
    container_name: lightpub_typesense
    profiles:
      - lightpub
    networks:
      - internal_network
      - external_network
