services:
  lightpub_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: release
    image: ghcr.io/lightpub-dev/lightpub:latest
    depends_on:
      lightpub_db:
        condition: service_healthy
      lightpub_kv:
        condition: service_started
      lightpub_nats:
        condition: service_started
    environment:
      DATABASE_URL: mysql://lightpub:lightpub@lightpub_db:3306/lightpub
      REDIS_URL: redis://lightpub_kv:6379
      NATS_URL: nats://lightpub_nats:4222
      TYPESENSE_URL: http://lightpub_typesense:8108
      TYPESENSE_API_KEY: xyz
      SESSION_KEY: BIXIR1GPwQJBjvIZ8rSeVVdt09IPfdeGfdFncS9tN0RjF9ziMckmgPUjS5uBOf47
      RUST_LOG: info,sqlx=warn
      JWT_PUBLIC_KEY_FILE: data/jwtpub.pem
      JWT_SECRET_KEY_FILE: data/jwt.pem
      TMP_DIR: /app/tmp
      UPLOAD_DIR: /app/uploads
      REGISTRATION_OPEN: true
      LP_BASE_URL: https://lp.tinax.local
      DEV_MODE: false
    volumes:
      - lightpub_data:/app/data
      - lightpub_uploads:/app/uploads
      - lightpub_tmp:/app/tmp
      - /tmp/lpdata:/tmp
    ports:
      - "127.0.0.1:8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    init: true

  lightpub_mathjax:
    image: ghcr.io/lightpub-dev/lightpub/mathjax:latest
    build:
      context: ./subsystems/mathjax
    environment:
      NATS_URL: nats://lightpub_nats:4222
    depends_on:
      lightpub_nats:
        condition: service_started
    init: true
    restart: unless-stopped

  lightpub_db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MARIADB_DATABASE=lightpub
      - MARIADB_USER=lightpub
      - MARIADB_PASSWORD=lightpub
      - MARIADB_ROOT_PASSWORD=lightpub
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mariadb_data:/var/lib/mysql
    command: mariadbd --collation-server utf8mb4_general_ci --performance-schema

  lightpub_kv:
    image: valkey/valkey:latest
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped

  lightpub_nats:
    image: nats:latest
    ports:
      - 127.0.0.1:4222:4222
    volumes:
      - nats_data:/data
    command: -js -sd /data
    restart: unless-stopped

  # For fulltext search
  lightpub_typesense:
    image: typesense/typesense:29.0.rc5
    restart: on-failure
    ports:
      - "127.0.0.1:8108:8108"
    volumes:
      - lightpub_typesense_data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"

volumes:
  nats_data:
  mariadb_data:
    name: lightpub_mariadb_data
  lightpub_data:
    name: lightpub_data
  lightpub_tmp:
    name: lightpub_tmp
  lightpub_uploads:
    name: lightpub_uploads
  lightpub_typesense_data:
