# Generated by Django 5.0.1 on 2024-01-21 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("host", models.CharField(max_length=128)),
                ("bpassword", models.CharField(max_length=60)),
                ("nickname", models.CharField(max_length=255)),
                ("bio", models.TextField(default="")),
                ("url", models.CharField(blank=True, max_length=512, null=True)),
                ("inbox", models.CharField(blank=True, max_length=512, null=True)),
                ("outbox", models.CharField(blank=True, max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(blank=True, max_length=10000, null=True)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "privacy",
                    models.SmallIntegerField(
                        choices=[
                            (0, "public"),
                            (1, "unlisted"),
                            (2, "follower"),
                            (3, "private"),
                        ]
                    ),
                ),
                ("edited", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="api.post",
                    ),
                ),
                (
                    "repost_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reposts",
                        to="api.post",
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostHashtag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hashtag", models.CharField(max_length=255)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashtags",
                        to="api.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostMention",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="api.post",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostFavorite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="api.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostBookmark",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="api.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="api.user",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followings",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileLabel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order", models.IntegerField()),
                ("key", models.CharField(max_length=1000)),
                ("value", models.CharField(max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="posthashtag",
            constraint=models.UniqueConstraint(
                fields=("post", "hashtag"), name="unique_post_hashtag"
            ),
        ),
        migrations.AddConstraint(
            model_name="postmention",
            constraint=models.UniqueConstraint(
                fields=("post", "target_user"), name="unique_post_mention"
            ),
        ),
        migrations.AddConstraint(
            model_name="postfavorite",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_post_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="postbookmark",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_post_bookmark"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.UniqueConstraint(
                fields=("follower", "followee"), name="unique_user_follow"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofilelabel",
            constraint=models.UniqueConstraint(
                fields=("user", "order"), name="unique_user_profile_label_order"
            ),
        ),
    ]
