# Generated by Django 5.0.1 on 2024-01-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
