# Generated by Django 5.0.2 on 2024-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_postreaction_postreaction_unique_post_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="host",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
