# Generated by Django 5.0.2 on 2024-02-19 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteUserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='remote_user_info', serialize=False, to='api.user')),
                ('following', models.CharField(blank=True, max_length=512, null=True)),
                ('followers', models.CharField(blank=True, max_length=512, null=True)),
                ('liked', models.CharField(blank=True, max_length=512, null=True)),
                ('preffered_username', models.CharField(blank=True, max_length=128, null=True)),
                ('last_fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='bpassword',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
