# Generated by Django 5.0.2 on 2024-02-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remoteuserinfo_alter_user_bpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteuserinfo',
            old_name='preffered_username',
            new_name='preferred_username',
        ),
    ]
