# Generated by Django 5.0.2 on 2024-02-19 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_preffered_username_remoteuserinfo_preferred_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('incoming', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_requests', to='api.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests', to='api.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userfollowrequest',
            constraint=models.UniqueConstraint(fields=('follower', 'followee'), name='unique_user_follow_request'),
        ),
    ]
