# Generated by Django 5.0.2 on 2024-02-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userfollowrequest_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowrequest',
            name='unique_user_follow_request',
        ),
    ]
