# Generated by Django 5.0.2 on 2024-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_publickey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="url",
            new_name="uri",
        ),
        migrations.RenameField(
            model_name="userfollowrequest",
            old_name="url",
            new_name="uri",
        ),
        migrations.AddField(
            model_name="post",
            name="uri",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
