# Generated by Django 5.0.2 on 2024-02-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_rename_url_user_uri_rename_url_userfollowrequest_uri_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedServer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("host", models.CharField(max_length=128, unique=True)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
