# Generated by Django 5.0.2 on 2024-02-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_post_partial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postbookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="postfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="api.user",
            ),
        ),
    ]
