# Generated by Django 5.0.2 on 2024-02-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_postbookmark_user_alter_postfavorite_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteuserinfo",
            name="shared_inbox",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
