# Generated by Django 5.0.2 on 2024-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remoteuserinfo_shared_inbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publickey",
            name="uri",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
