[package]
name = "lightpub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
bcrypt = "0.15"
chrono = "0.4.34"
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = "1.7.0"
valico = "2"

[dependencies.sea-orm]
version = "0.12.14"
features = ["sqlx-mysql", "runtime-tokio-rustls", "debug-print", "with-chrono", "with-json", "with-uuid"]
