version: "3.8" # Use a suitable version for your Docker engine and Compose file features

services:
  nginx:
    restart: unless-stopped
    container_name: lightpub-nginx-test
    image: nginx:bookworm
    volumes:
      - ./test_instances/nginx-test/conf.d:/etc/nginx/conf.d
      - ./test_instances/ssl:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      lightpub_test:
        aliases:
          - mastodon.tinax.local
          - misskey.tinax.local
          - lightpub.tinax.local
          - pleroma.tinax.local
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s
    depends_on:
      lightpub_api:
        condition: service_healthy

  lightpub_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: debug
    container_name: lightpub-server-test
    ports:
      - "8000:8000"
    networks:
      - lightpub_test
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "-w30", "127.0.0.1", "8000"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 60s
      start_interval: 2s
    depends_on:
      lightpub_db:
        condition: service_healthy
    volumes:
      - ./lightpub.yml.test:/lightpub/lightpub.yml.sample
    init: true # necessary for shutting down gracefully

  lightpub_db:
    image: mariadb:latest
    container_name: lightpub-test-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lightpub_test
      MYSQL_USER: lightpub
      MYSQL_PASSWORD: lightpub
    networks:
      - lightpub_test
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s

  test-runner:
    build: ./tests
    networks:
      - lightpub_test
    container_name: lightpub-test-runner
    depends_on:
      nginx:
        condition: service_healthy
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

networks:
  lightpub_test:
