version: '3.8' # Use a suitable version for your Docker engine and Compose file features

services:
  lightpub-db:
    image: mariadb:latest
    container_name: lightpub-db-test
    environment:
      MYSQL_USER: lightpub
      MYSQL_PASSWORD: lightpub
      MYSQL_ROOT_PASSWORD: lightpub
      MYSQL_DATABASE: lightpub
    ports:
      - "3306:3306"
    networks:
      - lightpub-test

  redis:
    image: redis:latest
    container_name: lightpub-redis-test
    ports:
      - "6380:6379"
    networks:
      - lightpub-test

  server:
    build: .
    container_name: lightpub-server
    ports:
      - "8000:8000"
    networks:
      - lightpub-test
  test-runner:
    build: ./tests
    container_name: lightpub-test-runner
    networks:
      - lightpub-test
networks:
  lightpub-test:
    external: false
