# spin up dev mariadb container
services:
  devdb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: lightpub
      MYSQL_DATABASE: lightpub
      MYSQL_USER: lightpub
      MYSQL_PASSWORD: lightpub
    ports:
      - 127.0.0.1:3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s
