version: '3.8'  # Use a suitable version for your Docker engine and Compose file features

services:
  lightpub-db:
    image: mariadb:latest
    container_name: lightpub-db
    environment:
      MYSQL_USER: lightpub
      MYSQL_PASSWORD: lightpub
      MYSQL_ROOT_PASSWORD: lightpub
      MYSQL_DATABASE: lightpub
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: lightpub-redis
    ports:
      - "6380:6379"
