version: "3.8" # Use a suitable version for your Docker engine and Compose file features

services:
  lightpub-db:
    image: postgres:latest
    container_name: misskey-db
    environment:
      POSTGRES_NAME: misskey
      POSTGRES_USER: misskey
      POSTGRES_PASSWORD: misskey
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: misskey-redis
    ports:
      - "6379:6379"
