ALTER TABLE lightpub.`User` ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE lightpub.`User` CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL AFTER outbox;
