ALTER TABLE
    `UserFollow`
MODIFY
    COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    `Post`
MODIFY
    COLUMN `inserted_at` DATETIME NOT NULL,
MODIFY
    COLUMN `created_at` DATETIME NOT NULL,
MODIFY
    COLUMN `scheduled_at` DATETIME DEFAULT NULL;

ALTER TABLE
    `PostPoll`
MODIFY
    COLUMN `due` DATETIME DEFAULT NULL;
