ALTER TABLE
    `UserFollow`
MODIFY
    COLUMN `created_at` DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE
    `Post`
MODIFY
    COLUMN `inserted_at` DATETIME(6) NOT NULL,
MODIFY
    COLUMN `created_at` DATETIME(6) NOT NULL,
MODIFY
    COLUMN `scheduled_at` DATETIME(6) DEFAULT NULL;

ALTER TABLE
    `PostPoll`
MODIFY
    COLUMN `due` DATETIME(6) DEFAULT NULL;
