name: server-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lightpub_test:
    name: Run Lightpub API tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          cd rs
          ./run_tests.sh
  misskey_federation_test:
    name: Run Misskey federation tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          cd rs
          ./run_federation_test.sh
